name: CI

on:
  workflow_dispatch:
    inputs:
      libraries:
        description: 'libraries'
        required: false
        type: string
  # im just including everything under scripts,
  # because its easier and it means i dont forget to add a script here
  # because theres certain scripts where if theyre changed, all tests should be ran
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/ci.yml"
      - "libs/**"
      - "scripts/**"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/ci.yml"
      - "scripts/**"
      - "libs/**"

jobs:
  Main:    
    runs-on: ${{ matrix.runner-os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            runner-os: windows-latest
  
          - name: Linux
            runner-os: ubuntu-latest
  
          - name: macOS
            runner-os: macos-14
        
    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Install Toolchain
        run: rokit install --no-trust-check

      - name: Run test runner
        env:
          GH_TOKEN: ${{ github.token }}
        run: lune run scripts/test_runner ${{ inputs.libraries }}
