name: CI

on:
  workflow_dispatch:
    inputs:
      skip:
        description: 'Test cases to skip (format: LIBNAME.TESTCASE or LIBNAME(...TESTCASE))'
        required: false
        type: string
  push:
    paths:
      - "scripts/diff_to_tbl.luau"
      - "scripts/test_runner.luau"
      - "scripts/depgraph.luau"
      - "testkit.luau"
  pull_request:
    paths:
      - "scripts/diff_to_tbl.luau"
      - "scripts/test_runner.luau"
      - "scripts/depgraph.luau"
      - "testkit.luau"

jobs:
  Main:    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            runner-os: windows-latest
  
          - name: Linux
            runner-os: ubuntu-latest
  
          - name: macOS
            runner-os: macos-14
        
    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/checkout@v3

      - name: Install Toolchain
        run: rokit install --no-trust-check

      - name: Fetch diff
        id: fetch_diff
        shell: bash
        run: |

      - name: Run test runner
        run: lune run scripts/test_runner
