name: Docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "docs/**"

concurrency:
  group: Docs
  cancel-in-progress: true

jobs:
  Docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/configure-pages@v2

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Toolchain
        run: rokit install --no-trust-check

      - name: Sort libraries
        run: lune run scripts/docs

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Build
        run: npm ci && npm run docs:build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist
          
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
