name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/checkout@v4

      - name: Install Toolchain
        run: rokit install --no-trust-check

      - name: Run releases script
        env:
          GH_TOKEN: ${{ github.token }}
        run: lune run scripts/release
